udp_bridge/remotes:
    vehicle:
        host: localhost
        port: 4200
        topics:
          - source: project11/command
            destination: project11/command
          - source: piloting_mode/manual/helm
            destination: piloting_mode/manual/helm
