name: ROS CI

on:
  push:
    branches: [ noetic ]
  pull_request:
    branches: [ noetic ]

jobs:
  build_docker:
    runs-on: ubuntu-latest

    container:
      image: osrf/ros:noetic-desktop-full-focal

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    
