name: ROS CI

on:
  push:
    branches: [ noetic ]
  pull_request:
    branches: [ noetic ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - if: runner.os == 'Linux'
      # azure ubuntu repo can be flaky so add an alternate source
      run: sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list
    - name: Install ROS
      uses: ros-tooling/setup-ros@0.1.1
      with:
        required-ros-distributions: noetic
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
