name: ROS CI

on:
  push:
    branches: [ noetic ]
  pull_request:
    branches: [ noetic ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install ROS
      uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: noetic
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
